name: 'Hello world'
description: 'Greet someone'
inputs:
  who-to-greet: # id of the input
    description: 'who to greet'
    required: true
    default: 'world'
outputs:
  time:
    description: 'The time we greeted'
runs:
  using: 'node12'
  main: 'index.js'
